### PR TITLE
Fix rubber (again)

### PR DESCRIPTION
**Pull request by NCBPFluffyBear**
## Short Description
Biscuit found an issue with the change, this fixes it.

## Additions/Changes/Removals
The variable is set after the server determines if SlimyTreeTaps is installed or not.

## Related Issues
#45 #49 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Comment by WalshyDev** [comment]
Just to note, this is why we have a "I have tested" checkbox. I wanted you to find out by people complaining but Cookie had to ruin my fun

**Comment by WalshyDev** [comment]
Also how is this a "fix" you just went back to the original broken problem rather than moving the variable.

**Comment by NCBPFluffyBear** [comment]
Its initialized but it doesnt request the item before the server decides which one to use

**Comment by NCBPFluffyBear** [comment]
oh wtf its not the right commit

**Comment by NCBPFluffyBear** [comment]
Oh this isnt even the right kind of pr i think it drafted the revert

**Comment by TheBusyBiscuit** [comment]
> Just to note, this is why we have a "I have tested" checkbox. I wanted you to find out by people complaining but Cookie had to ruin my fun

Well, that's still just poor code review from your side too >.>

**Comment by WalshyDev** [comment]
> Well, that's still just poor code review from your side too >.>

> I wanted you to find out by people complaining but Cookie had to ruin my fun

Also I was busy and Panda was requesting me to view. I don't care about pushing shit just to prove a point when people complain.

**Pull request closed without merging**
