### PR TITLE
Prevent dying of sheep using UU Matter and any future dye items

### PR DESCRIPTION
**Pull request by NCBPFluffyBear**
## Short Description
Added DyeItem, which can be extended to prevent animal and sign dying
Registered UU Matter as a DyeItem

## Additions/Changes/Removals
Added DyeItem
Added event handler to prevent mob interactions

## Related Issues
N/A

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Comment by J3fftw1** [comment]
Please place comments on stuff. In December i wanna do it all over the project beginning from now will be a good thing

**Comment by J3fftw1** [comment]
what about the other items

**Comment by NCBPFluffyBear** [comment]
bop look at this

**Comment by TheBusyBiscuit** [comment]
UU Sheep when?

**Comment by J3fftw1** [comment]
fix conflics and i will merge

**Pull request merged**
